import { PrismaClient, Difficulty } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Start seeding...');
  // Purane data ko delete karein taaki conflicts na ho
  await prisma.matchParticipant.deleteMany();
  await prisma.room.deleteMany();
  await prisma.problem.deleteMany();

  console.log('Old data deleted successfully.');

  const problemsToCreate = [
    // ----------------- ARRAYS & HASHING -----------------
    {
      id: '1',
      title: 'Indices for Target Sum',
      slug: 'indices-for-target-sum',
      description: 'You are given a list of numbers and a specific target value. Your task is to find two numbers in this list that sum up to the target. Return the indices of these two numbers.',
      difficulty: Difficulty.EASY,
      functionName: 'findPairSum',
      inputSignature: [{ name: 'nums', type: 'integer[]' }, { name: 'target', type: 'integer' }],
      testCases: { "Input": "[10,20,30,40]\n50", "Output": "[1,2]" },
      StarterCode: {
        javascript: 'var findPairSum = function(nums, target) {\n    // Your code here\n};',
        python: 'class Solution:\n    def findPairSum(self, nums: list[int], target: int) -> list[int]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    vector<int> findPairSum(vector<int>& nums, int target) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int[] findPairSum(int[] nums, int target) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '30',
      title: 'Find Duplicates in Array',
      slug: 'find-duplicates-in-array',
      description: 'Given an integer array `nums`, return `true` if any value appears at least twice in the array, and return `false` if every element is distinct.',
      difficulty: Difficulty.EASY,
      functionName: 'containsDuplicate',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[1,2,3,1]\n", "Output": "true" },
      StarterCode: {
        javascript: 'var containsDuplicate = function(nums) {\n    // Your code here\n};',
        python: 'class Solution:\n    def containsDuplicate(self, nums: list[int]) -> bool:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    bool containsDuplicate(vector<int>& nums) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public boolean containsDuplicate(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '17',
      title: 'Product of Others',
      slug: 'product-of-others',
      description: 'Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all the elements of `nums` except `nums[i]`. You must write an algorithm that runs in O(n) time and without using the division operation.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'productExceptSelf',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[1,2,3,4]\n", "Output": "[24,12,8,6]" },
      StarterCode: {
        javascript: 'var productExceptSelf = function(nums) {\n    // Your code here\n};',
        python: 'class Solution:\n    def productExceptSelf(self, nums: list[int]) -> list[int]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    vector<int> productExceptSelf(vector<int>& nums) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int[] productExceptSelf(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
     {
      id: '12',
      title: 'Most Frequent K Numbers',
      slug: 'most-frequent-k-numbers',
      description: 'From a given list of numbers, find the `k` elements that appear most frequently. You can return the result in any order.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'topKFrequent',
      inputSignature: [{ name: 'nums', type: 'integer[]' }, { name: 'k', type: 'integer' }],
      testCases: { "Input": "[4,1,-1,2,-1,2,3]\n2", "Output": "[-1,2]" },
      StarterCode: {
          javascript: 'var topKFrequent = function(nums, k) {\n    // Your code here\n};',
          python: 'class Solution:\n    def topKFrequent(self, nums: list[int], k: int) -> list[int]:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    vector<int> topKFrequent(vector<int>& nums, int k) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int[] topKFrequent(int[] nums, int k) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '16',
      title: 'Zero Sum Triplets',
      slug: 'zero-sum-triplets',
      description: 'Given an integer array `nums`, find all unique triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and their sum is zero.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'findZeroSumTriplets',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[-1,0,1,2,-1,-4]\n", "Output": "[[-1,-1,2],[-1,0,1]]" },
      StarterCode: {
        javascript: 'var findZeroSumTriplets = function(nums) {\n    // Your code here\n};',
        python: 'class Solution:\n    def findZeroSumTriplets(self, nums: list[int]) -> list[list[int]]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    vector<vector<int>> findZeroSumTriplets(vector<int>& nums) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public List<List<Integer>> findZeroSumTriplets(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },

    // ----------------- TWO POINTERS -----------------
     {
      id: '3',
      title: 'Palindrome String Check',
      slug: 'palindrome-string-check',
      description: "You are given a string. Determine if it's a palindrome after you convert it to lowercase and remove all characters that are not letters or numbers. Return true if it is, and false otherwise.",
      difficulty: Difficulty.EASY,
      functionName: 'isPalindrome',
      inputSignature: [{ name: 's', type: 'string' }],
      testCases: { "Input": "Was it a car or a cat I saw?\n", "Output": "true" },
      StarterCode: {
        javascript: 'var isPalindrome = function(s) {\n    // Your code here\n};',
        python: 'class Solution:\n    def isPalindrome(self, s: str) -> bool:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    bool isPalindrome(string s) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public boolean isPalindrome(String s) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '2',
      title: 'Maximum Water Storage',
      slug: 'maximum-water-storage',
      description: 'Imagine a series of vertical bars of different heights. You need to select two bars that, when used as the sides of a container, can hold the maximum amount of water. Return this maximum capacity.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'maxAreaContainer',
      inputSignature: [{ name: 'height', type: 'integer[]' }],
      testCases: { "Input": "[2,3,4,5,18,17,6]\n", "Output": "17" },
      StarterCode: {
        javascript: 'var maxAreaContainer = function(height) {\n    // Your code here\n};',
        python: 'class Solution:\n    def maxAreaContainer(self, height: list[int]) -> int:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    int maxAreaContainer(vector<int>& height) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int maxAreaContainer(int[] height) {\n        // Your code here\n    }\n}',
      },
    },

    // ----------------- STRINGS -----------------
     {
        id: '4',
        title: 'Longest Unique Substring',
        slug: 'longest-unique-substring',
        description: 'From a given string, find the length of the longest possible substring that does not contain any repeating characters.',
        difficulty: Difficulty.MEDIUM,
        functionName: 'lengthOfLongestSubstring',
        inputSignature: [{ name: 's', type: 'string' }],
        testCases: { "Input": "pwwkew\n", "Output": "3" },
        StarterCode: {
          javascript: 'var lengthOfLongestSubstring = function(s) {\n    // Your code here\n};',
          python: 'class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int lengthOfLongestSubstring(string s) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        // Your code here\n    }\n}',
        },
    },
    {
      id: '19',
      title: 'Anagram Check',
      slug: 'anagram-check',
      description: 'Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise. An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.',
      difficulty: Difficulty.EASY,
      functionName: 'isAnagram',
      inputSignature: [{ name: 's', type: 'string' }, { name: 't', type: 'string' }],
      testCases: { "Input": "anagram\nnagaram", "Output": "true" },
      StarterCode: {
        javascript: 'var isAnagram = function(s, t) {\n    // Your code here\n};',
        python: 'class Solution:\n    def isAnagram(self, s: str, t: str) -> bool:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public boolean isAnagram(String s, String t) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '20',
      title: 'Group by Anagrams',
      slug: 'group-by-anagrams',
      description: 'Given an array of strings `strs`, group the anagrams together. You can return the answer in any order.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'groupAnagrams',
      inputSignature: [{ name: 'strs', type: 'string[]' }],
      testCases: { "Input": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]\n", "Output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]" },
      StarterCode: {
        javascript: 'var groupAnagrams = function(strs) {\n    // Your code here\n};',
        python: 'class Solution:\n    def groupAnagrams(self, strs: list[str]) -> list[list[str]]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    vector<vector<string>> groupAnagrams(vector<string>& strs) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public List<List<String>> groupAnagrams(String[] strs) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '31',
      title: 'Longest Palindromic Subsequence',
      slug: 'longest-palindromic-subsequence',
      description: 'Given a string `s`, find the longest palindromic substring in `s`.',
      difficulty: Difficulty.HARD,
      functionName: 'longestPalindrome',
      inputSignature: [{ name: 's', type: 'string' }],
      testCases: { "Input": "babad\n", "Output": "bab" },
      StarterCode: {
          javascript: 'var longestPalindrome = function(s) {\n    // Your code here\n};',
          python: 'class Solution:\n    def longestPalindrome(self, s: str) -> str:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    string longestPalindrome(string s) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public String longestPalindrome(String s) {\n        // Your code here\n    }\n}',
      },
    },

    // ----------------- LINKED LISTS -----------------
    {
        id: '5',
        title: 'Invert Linked List',
        slug: 'invert-linked-list',
        description: 'You are provided with the head of a singly linked list. Your task is to reverse the order of the nodes and return the new head of the inverted list.',
        difficulty: Difficulty.EASY,
        functionName: 'reverseList',
        inputSignature: [{ name: 'head', type: 'integer[]' }],
        testCases: { "Input": "[10,20,30]\n", "Output": "[30,20,10]" },
        StarterCode: {
          javascript: '/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n * this.val = (val===undefined ? 0 : val)\n * this.next = (next===undefined ? null : next)\n * }\n */\nvar reverseList = function(head) {\n    // Your code here\n};',
          python: '# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:\n        # Your code here\n        pass',
          cpp: '/**\n * Definition for singly-linked list.\n * struct ListNode {\n * int val;\n * ListNode *next;\n * ListNode() : val(0), next(nullptr) {}\n * ListNode(int x) : val(x), next(nullptr) {}\n * ListNode(int x, ListNode *next) : val(x), next(next) {}\n * };\n */\nclass Solution {\npublic:\n    ListNode* reverseList(ListNode* head) {\n        // Your code here\n    }\n};',
          java: '/**\n * Definition for singly-linked list.\n * public class ListNode {\n * int val;\n * ListNode next;\n * ListNode() {}\n * ListNode(int val) { this.val = val; }\n * ListNode(int val, ListNode next) { this.val = val; this.next = next; }\n * }\n */\nclass Solution {\n    public ListNode reverseList(ListNode head) {\n        // Your code here\n    }\n}',
        },
    },
     {
      id: '21',
      title: 'Combine Sorted Lists',
      slug: 'combine-sorted-lists',
      description: 'You are given the heads of two sorted linked lists `list1` and `list2`. Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.',
      difficulty: Difficulty.EASY,
      functionName: 'mergeTwoLists',
      inputSignature: [{ name: 'list1', type: 'integer[]' }, { name: 'list2', type: 'integer[]' }],
      testCases: { "Input": "[1,2,4]\n[1,3,4]", "Output": "[1,1,2,3,4,4]" },
      StarterCode: {
        javascript: 'var mergeTwoLists = function(list1, list2) {\n    // Your code here\n};',
        python: 'class Solution:\n    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    ListNode* mergeTwoLists(ListNode* list1, ListNode* list2) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public ListNode mergeTwoLists(ListNode list1, ListNode list2) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '32',
      title: 'Remove Nth Last Node',
      slug: 'remove-nth-last-node',
      description: 'Given the `head` of a linked list, remove the `n`th node from the end of the list and return its head.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'removeNthFromEnd',
      inputSignature: [{ name: 'head', type: 'integer[]' }, { name: 'n', type: 'integer' }],
      testCases: { "Input": "[1,2,3,4,5]\n2", "Output": "[1,2,3,5]" },
      StarterCode: {
          javascript: 'var removeNthFromEnd = function(head, n) {\n    // Your code here\n};',
          python: 'class Solution:\n    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    ListNode* removeNthFromEnd(ListNode* head, int n) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public ListNode removeNthFromEnd(ListNode head, int n) {\n        // Your code here\n    }\n}',
      },
    },
    {
        id: '6',
        title: 'Find Loop in Linked List',
        slug: 'find-loop-in-linked-list',
        description: "You are given the head of a linked list. Check if it contains a cycle (i.e., a node points back to a previous node). Return true if a cycle exists, false otherwise.",
        difficulty: Difficulty.MEDIUM,
        functionName: 'hasCycle',
        inputSignature: [{ name: 'head', type: 'integer[]' }, { name: 'pos', type: 'integer' }],
        testCases: { "Input": "[1,2]\n0", "Output": "true" },
        StarterCode: {
          javascript: 'var hasCycle = function(head) {\n    // Your code here\n};',
          python: 'class Solution:\n    def hasCycle(self, head: Optional[ListNode]) -> bool:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    bool hasCycle(ListNode *head) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public boolean hasCycle(ListNode head) {\n        // Your code here\n    }\n}',
        },
    },

    // ----------------- TREES -----------------
     {
        id: '7',
        title: 'Tree Height Calculation',
        slug: 'tree-height-calculation',
        description: 'Calculate the maximum depth of a given binary tree. The depth is the number of nodes along the longest path from the root node down to the farthest leaf node.',
        difficulty: Difficulty.EASY,
        functionName: 'maxDepth',
        inputSignature: [{ name: 'root', type: 'tree' }],
        testCases: { "Input": "[1,null,2]\n", "Output": "2" },
        StarterCode: {
          javascript: 'var maxDepth = function(root) {\n    // Your code here\n};',
          python: 'class Solution:\n    def maxDepth(self, root: Optional[TreeNode]) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int maxDepth(TreeNode* root) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int maxDepth(TreeNode root) {\n        // Your code here\n    }\n}',
        },
    },
    {
      id: '22',
      title: 'Mirror a Binary Tree',
      slug: 'mirror-binary-tree',
      description: 'Given the `root` of a binary tree, invert the tree, and return its root. Inverting a tree means swapping the left and right children of every node.',
      difficulty: Difficulty.EASY,
      functionName: 'invertTree',
      inputSignature: [{ name: 'root', type: 'tree' }],
      testCases: { "Input": "[4,2,7,1,3,6,9]\n", "Output": "[4,7,2,9,6,3,1]" },
      StarterCode: {
        javascript: 'var invertTree = function(root) {\n    // Your code here\n};',
        python: 'class Solution:\n    def invertTree(self, root: Optional[TreeNode]) -> Optional[TreeNode]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    TreeNode* invertTree(TreeNode* root) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public TreeNode invertTree(TreeNode root) {\n        // Your code here\n    }\n}',
      },
    },
    {
        id: '8',
        title: 'Verify BST Property',
        slug: 'verify-bst-property',
        description: 'You are given the root of a binary tree. Check if it is a valid Binary Search Tree (BST). A BST is valid if for every node, all values in its left subtree are smaller, and all values in its right subtree are larger.',
        difficulty: Difficulty.MEDIUM,
        functionName: 'isValidBST',
        inputSignature: [{ name: 'root', type: 'tree' }],
        testCases: { "Input": "[2,1,3]\n", "Output": "true" },
        StarterCode: {
          javascript: 'var isValidBST = function(root) {\n    // Your code here\n};',
          python: 'class Solution:\n    def isValidBST(self, root: Optional[TreeNode]) -> bool:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    bool isValidBST(TreeNode* root) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public boolean isValidBST(TreeNode root) {\n        // Your code here\n    }\n}',
        },
    },
    {
      id: '33',
      title: 'Kth Smallest in BST',
      slug: 'kth-smallest-in-bst',
      description: 'Given the `root` of a binary search tree, and an integer `k`, return the `k`th smallest value (1-indexed) of all the values of the nodes in the tree.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'kthSmallest',
      inputSignature: [{ name: 'root', type: 'tree' }, { name: 'k', type: 'integer' }],
      testCases: { "Input": "[3,1,4,null,2]\n1", "Output": "1" },
      StarterCode: {
          javascript: 'var kthSmallest = function(root, k) {\n    // Your code here\n};',
          python: 'class Solution:\n    def kthSmallest(self, root: Optional[TreeNode], k: int) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int kthSmallest(TreeNode* root, int k) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int kthSmallest(TreeNode root, int k) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '34',
      title: 'BST Common Ancestor',
      slug: 'bst-common-ancestor',
      description: 'Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST. The lowest common ancestor is defined between two nodes `p` and `q` as the lowest node in `T` that has both `p` and `q` as descendants.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'lowestCommonAncestor',
      inputSignature: [{ name: 'root', type: 'tree' }, { name: 'p', type: 'integer' }, { name: 'q', type: 'integer' }],
      testCases: { "Input": "[6,2,8,0,4,7,9,null,null,3,5]\n2\n8", "Output": "6" },
      StarterCode: {
          javascript: 'var lowestCommonAncestor = function(root, p, q) {\n    // Your code here\n};',
          python: 'class Solution:\n    def lowestCommonAncestor(self, root: "TreeNode", p: "TreeNode", q: "TreeNode") -> "TreeNode":\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n        // Your code here\n    }\n}',
      },
    },

    // ----------------- DYNAMIC PROGRAMMING -----------------
    {
        id: '9',
        title: 'Staircase Step Combinations',
        slug: 'staircase-step-combinations',
        description: 'You need to climb a staircase with `n` steps. You can take either 1 or 2 steps at a time. Calculate the total number of distinct ways you can reach the top.',
        difficulty: Difficulty.EASY,
        functionName: 'climbStairs',
        inputSignature: [{ name: 'n', type: 'integer' }],
        testCases: { "Input": "4\n", "Output": "5" },
        StarterCode: {
          javascript: 'var climbStairs = function(n) {\n    // Your code here\n};',
          python: 'class Solution:\n    def climbStairs(self, n: int) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int climbStairs(int n) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int climbStairs(int n) {\n        // Your code here\n    }\n}',
        },
    },
    {
      id: '23',
      title: 'Street Robbery',
      slug: 'street-robbery',
      description: 'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. The only constraint is that adjacent houses have security systems connected, and will alert the police if two adjacent houses are broken into. Given an integer array `nums` representing the amount of money of each house, return the maximum amount of money you can rob without alerting the police.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'rob',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[2,7,9,3,1]\n", "Output": "12" },
      StarterCode: {
        javascript: 'var rob = function(nums) {\n    // Your code here\n};',
        python: 'class Solution:\n    def rob(self, nums: list[int]) -> int:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    int rob(vector<int>& nums) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int rob(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
    {
        id: '10',
        title: 'Minimum Coin Combination',
        slug: 'minimum-coin-combination',
        description: "Given a set of coin denominations and a total amount, determine the minimum number of coins required to make up that amount. If it's impossible, return -1.",
        difficulty: Difficulty.MEDIUM,
        functionName: 'coinChange',
        inputSignature: [{ name: 'coins', type: 'integer[]' }, { name: 'amount', type: 'integer' }],
        testCases: { "Input": "[2]\n3", "Output": "-1" },
        StarterCode: {
          javascript: 'var coinChange = function(coins, amount) {\n    // Your code here\n};',
          python: 'class Solution:\n    def coinChange(self, coins: list[int], amount: int) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int coinChange(vector<int>& coins, int amount) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int coinChange(int[] coins, int amount) {\n        // Your code here\n    }\n}',
        },
    },
    {
      id: '24',
      title: 'Longest Ascending Sequence',
      slug: 'longest-ascending-sequence',
      description: 'Given an integer array `nums`, return the length of the longest strictly increasing subsequence.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'lengthOfLIS',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[10,9,2,5,3,7,101,18]\n", "Output": "4" },
      StarterCode: {
        javascript: 'var lengthOfLIS = function(nums) {\n    // Your code here\n};',
        python: 'class Solution:\n    def lengthOfLIS(self, nums: list[int]) -> int:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    int lengthOfLIS(vector<int>& nums) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int lengthOfLIS(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },

    // ----------------- GRAPHS -----------------
    {
        id: '11',
        title: 'Count Land Masses',
        slug: 'count-land-masses',
        description: "You are given a 2D grid map where '1' represents land and '0' represents water. An island is a group of connected '1's. Your task is to count the total number of separate islands on the map.",
        difficulty: Difficulty.MEDIUM,
        functionName: 'numIslands',
        inputSignature: [{ name: 'grid', type: 'string[][]' }],
        testCases: { "Input": "[[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]\n", "Output": "1" },
        StarterCode: {
          javascript: 'var numIslands = function(grid) {\n    // Your code here\n};',
          python: 'class Solution:\n    def numIslands(self, grid: list[list[str]]) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int numIslands(vector<vector<char>>& grid) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int numIslands(char[][] grid) {\n        // Your code here\n    }\n}',
        },
    },
    {
      id: '25',
      title: 'Duplicate Graph Structure',
      slug: 'duplicate-graph-structure',
      description: 'Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph. Each node in the graph contains a value and a list of its neighbors.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'cloneGraph',
      inputSignature: [{ name: 'graph', type: 'graph' }],
      testCases: { "Input": "[[2,4],[1,3],[2,4],[1,3]]\n", "Output": "[[2,4],[1,3],[2,4],[1,3]]" },
      StarterCode: {
        javascript: 'var cloneGraph = function(node) {\n    // Your code here\n};',
        python: 'class Solution:\n    def cloneGraph(self, node: "Node") -> "Node":\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    Node* cloneGraph(Node* node) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public Node cloneGraph(Node node) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '26',
      title: 'Course Completion Check',
      slug: 'course-completion-check',
      description: 'There are a total of `numCourses` courses you have to take, labeled from 0 to `numCourses - 1`. You are given an array `prerequisites` where `prerequisites[i] = [ai, bi]` indicates that you must take course `bi` first if you want to take course `ai`. Return `true` if you can finish all courses. Otherwise, return `false`.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'canFinish',
      inputSignature: [{ name: 'numCourses', type: 'integer' }, { name: 'prerequisites', type: 'integer[][]' }],
      testCases: { "Input": "2\n[[1,0]]", "Output": "true" },
      StarterCode: {
        javascript: 'var canFinish = function(numCourses, prerequisites) {\n    // Your code here\n};',
        python: 'class Solution:\n    def canFinish(self, numCourses: int, prerequisites: list[list[int]]) -> bool:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        // Your code here\n    }\n}',
      },
    },
    
    // ----------------- OTHER TOPICS -----------------
    {
      id: '18',
      title: 'Maximize Stock Profit',
      slug: 'maximize-stock-profit',
      description: 'You are given an array `prices` where `prices[i]` is the price of a given stock on the `i`th day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve. If you cannot achieve any profit, return 0.',
      difficulty: Difficulty.EASY,
      functionName: 'maxProfit',
      inputSignature: [{ name: 'prices', type: 'integer[]' }],
      testCases: { "Input": "[7,1,5,3,6,4]\n", "Output": "5" },
      StarterCode: {
        javascript: 'var maxProfit = function(prices) {\n    // Your code here\n};',
        python: 'class Solution:\n    def maxProfit(self, prices: list[int]) -> int:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    int maxProfit(vector<int>& prices) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int maxProfit(int[] prices) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '13',
      title: 'Smallest Covering Substring',
      slug: 'smallest-covering-substring',
      description: "You are given two strings, `s` (the search string) and `t` (the pattern). Find the smallest substring in `s` that contains all the characters of `t`. If no such window exists, return an empty string.",
      difficulty: Difficulty.HARD,
      functionName: 'minWindow',
      inputSignature: [{ name: 's', type: 'string' }, { name: 't', type: 'string' }],
      testCases: { "Input": "a\na", "Output": "a" },
      StarterCode: {
        javascript: 'var minWindow = function(s, t) {\n    // Your code here\n};',
        python: 'class Solution:\n    def minWindow(self, s: str, t: str) -> str:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    string minWindow(string s, string t) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public String minWindow(String s, String t) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '14',
      title: 'Matrix 90-Degree Rotation',
      slug: 'matrix-90-degree-rotation',
      description: "Given a square matrix (n x n), rotate it 90 degrees clockwise. The challenge is to perform this rotation without using any extra matrix for storage (in-place).",
      difficulty: Difficulty.MEDIUM,
      functionName: 'rotate',
      inputSignature: [{ name: 'matrix', type: 'integer[][]' }],
      testCases: { "Input": "[[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]\n", "Output": "[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]" },
      StarterCode: {
        javascript: 'var rotate = function(matrix) {\n    // Your code here\n};',
        python: 'class Solution:\n    def rotate(self, matrix: list[list[int]]) -> None:\n        """\n        Do not return anything, modify matrix in-place instead.\n        """\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    void rotate(vector<vector<int>>& matrix) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public void rotate(int[][] matrix) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '15',
      title: 'Count Set Bits',
      slug: 'count-set-bits',
      description: "Given a 32-bit unsigned integer, count and return the number of '1's in its binary representation. This is also known as its Hamming weight.",
      difficulty: Difficulty.EASY,
      functionName: 'hammingWeight',
      inputSignature: [{ name: 'n', type: 'integer' }],
      testCases: { "Input": "11111111111111111111111111111101\n", "Output": "31" },
      StarterCode: {
        javascript: 'var hammingWeight = function(n) {\n    // Your code here\n};',
        python: 'class Solution:\n    def hammingWeight(self, n: int) -> int:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    int hammingWeight(uint32_t n) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    // you need to treat n as an unsigned value\n    public int hammingWeight(int n) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '29',
      title: 'Combine Overlapping Intervals',
      slug: 'combine-overlapping-intervals',
      description: 'Given an array of `intervals` where `intervals[i] = [start_i, end_i]`, merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'merge',
      inputSignature: [{ name: 'intervals', type: 'integer[][]' }],
      testCases: { "Input": "[[1,3],[2,6],[8,10],[15,18]]\n", "Output": "[[1,6],[8,10],[15,18]]" },
      StarterCode: {
        javascript: 'var merge = function(intervals) {\n    // Your code here\n};',
        python: 'class Solution:\n    def merge(self, intervals: list[list[int]]) -> list[list[int]]:\n        # Your code here\n        pass',
        cpp: 'class Solution {\npublic:\n    vector<vector<int>> merge(vector<vector<int>>& intervals) {\n        // Your code here\n    }\n};',
        java: 'class Solution {\n    public int[][] merge(int[][] intervals) {\n        // Your code here\n    }\n}',
      },
    },
     {
      id: '36',
      title: 'Valid Parentheses',
      slug: 'valid-parentheses',
      description: 'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid. An input string is valid if: open brackets must be closed by the same type of brackets, and open brackets must be closed in the correct order.',
      difficulty: Difficulty.EASY,
      functionName: 'isValidParentheses',
      inputSignature: [{ name: 's', type: 'string' }],
      testCases: { "Input": "()[]{}\n", "Output": "true" },
      StarterCode: {
          javascript: 'var isValidParentheses = function(s) {\n    // Your code here\n};',
          python: 'class Solution:\n    def isValidParentheses(self, s: str) -> bool:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    bool isValidParentheses(string s) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public boolean isValidParentheses(String s) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '37',
      title: 'Binary Search',
      slug: 'binary-search',
      description: 'Given an array of integers `nums` which is sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`. If `target` exists, then return its index. Otherwise, return -1.',
      difficulty: Difficulty.EASY,
      functionName: 'binarySearch',
      inputSignature: [{ name: 'nums', type: 'integer[]' }, { name: 'target', type: 'integer' }],
      testCases: { "Input": "[-1,0,3,5,9,12]\n9", "Output": "4" },
      StarterCode: {
          javascript: 'var binarySearch = function(nums, target) {\n    // Your code here\n};',
          python: 'class Solution:\n    def binarySearch(self, nums: list[int], target: int) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int binarySearch(vector<int>& nums, int target) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int binarySearch(int[] nums, int target) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '38',
      title: 'Minimum in Rotated Sorted Array',
      slug: 'min-rotated-sorted-array',
      description: 'Suppose an array of length `n` sorted in ascending order is rotated between 1 and `n` times. Given the sorted rotated array `nums` of unique elements, return the minimum element of this array.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'findMin',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[3,4,5,1,2]\n", "Output": "1" },
      StarterCode: {
          javascript: 'var findMin = function(nums) {\n    // Your code here\n};',
          python: 'class Solution:\n    def findMin(self, nums: list[int]) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int findMin(vector<int>& nums) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int findMin(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '39',
      title: 'Longest Repeating Character Replacement',
      slug: 'longest-repeating-char-replacement',
      description: 'You are given a string `s` and an integer `k`. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most `k` times. Return the length of the longest substring containing the same letter you can get after performing the above operations.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'characterReplacement',
      inputSignature: [{ name: 's', type: 'string' }, { name: 'k', type: 'integer' }],
      testCases: { "Input": "ABAB\n2", "Output": "4" },
      StarterCode: {
          javascript: 'var characterReplacement = function(s, k) {\n    // Your code here\n};',
          python: 'class Solution:\n    def characterReplacement(self, s: str, k: int) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int characterReplacement(string s, int k) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int characterReplacement(String s, int k) {\n        // Your code here\n    }\n}',
      },
    },
     {
      id: '40',
      title: 'Maximum Subarray Sum',
      slug: 'maximum-subarray-sum',
      description: 'Given an integer array `nums`, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.',
      difficulty: Difficulty.EASY,
      functionName: 'maxSubArray',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[-2,1,-3,4,-1,2,1,-5,4]\n", "Output": "6" },
      StarterCode: {
          javascript: 'var maxSubArray = function(nums) {\n    // Your code here\n};',
          python: 'class Solution:\n    def maxSubArray(self, nums: list[int]) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int maxSubArray(vector<int>& nums) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int maxSubArray(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '41',
      title: 'Jump Game',
      slug: 'jump-game',
      description: 'You are given an integer array `nums`. You are initially positioned at the array\'s first index, and each element in the array represents your maximum jump length at that position. Return `true` if you can reach the last index, or `false` otherwise.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'canJump',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[2,3,1,1,4]\n", "Output": "true" },
      StarterCode: {
          javascript: 'var canJump = function(nums) {\n    // Your code here\n};',
          python: 'class Solution:\n    def canJump(self, nums: list[int]) -> bool:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    bool canJump(vector<int>& nums) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public boolean canJump(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
     {
      id: '42',
      title: 'Subset Generation',
      slug: 'subset-generation',
      description: 'Given an integer array `nums` of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'subsets',
      inputSignature: [{ name: 'nums', type: 'integer[]' }],
      testCases: { "Input": "[1,2,3]\n", "Output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]" },
      StarterCode: {
          javascript: 'var subsets = function(nums) {\n    // Your code here\n};',
          python: 'class Solution:\n    def subsets(self, nums: list[int]) -> list[list[int]]:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    vector<vector<int>> subsets(vector<int>& nums) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '43',
      title: 'Word Break',
      slug: 'word-break',
      description: 'Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words. Note that the same word in the dictionary may be reused multiple times in the segmentation.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'wordBreak',
      inputSignature: [{ name: 's', type: 'string' }, { name: 'wordDict', type: 'string[]' }],
      testCases: { "Input": "leetcode\n[\"leet\",\"code\"]", "Output": "true" },
      StarterCode: {
          javascript: 'var wordBreak = function(s, wordDict) {\n    // Your code here\n};',
          python: 'class Solution:\n    def wordBreak(self, s: str, wordDict: list[str]) -> bool:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    bool wordBreak(string s, vector<string>& wordDict) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public boolean wordBreak(String s, List<String> wordDict) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '44',
      title: 'Combination Sum',
      slug: 'combination-sum',
      description: 'Given an array of distinct integers `candidates` and a target integer `target`, return a list of all unique combinations of `candidates` where the chosen numbers sum to `target`. You may return the combinations in any order.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'combinationSum',
      inputSignature: [{ name: 'candidates', type: 'integer[]' }, { name: 'target', type: 'integer' }],
      testCases: { "Input": "[2,3,6,7]\n7", "Output": "[[2,2,3],[7]]" },
      StarterCode: {
          javascript: 'var combinationSum = function(candidates, target) {\n    // Your code here\n};',
          python: 'class Solution:\n    def combinationSum(self, candidates: list[int], target: int) -> list[list[int]]:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    vector<vector<int>> combinationSum(vector<int>& candidates, int target) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n        // Your code here\n    }\n}',
      },
    },
    {
      id: '45',
      title: 'Reverse Integer',
      slug: 'reverse-integer',
      description: 'Given a signed 32-bit integer `x`, reverse digits of an integer. If reversing `x` causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.',
      difficulty: Difficulty.MEDIUM,
      functionName: 'reverse',
      inputSignature: [{ name: 'x', type: 'integer' }],
      testCases: { "Input": "123\n", "Output": "321" },
      StarterCode: {
          javascript: 'var reverse = function(x) {\n    // Your code here\n};',
          python: 'class Solution:\n    def reverse(self, x: int) -> int:\n        # Your code here\n        pass',
          cpp: 'class Solution {\npublic:\n    int reverse(int x) {\n        // Your code here\n    }\n};',
          java: 'class Solution {\n    public int reverse(int x) {\n        // Your code here\n    }\n}',
      },
    },
    // Add more problems here to reach 90-100 by following the pattern
  ];

  for (const problemData of problemsToCreate) {
    await prisma.problem.create({
      data: problemData,
    });
  }

  console.log(`Seeding finished. ${problemsToCreate.length} problems created.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
